config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks", registrations: "users/registrations" }
  
  resources :todo_lists do
    resources :todo_items, :comments do
      member do
        patch :complete
      end
    end
  end
  
  root "todo_lists#index"
  post "todo_lists/comment" => "todo_lists#comment"
  #get "/todo_lists/:todo_list_id"
  get "/todo_items/complete"=>"todo_items#complete"
  #post "todo_items/complete" => "todo_items#complete"
  #post "" => "todo_items#complete"
  post "todo_items/upload/:id" => 'todo_items#upload', as: :todo_item_upload
  get '/mypage/home' => 'mypage#home'
  get 'mypage/check'
  get '/todo_lists/main' =>'todo_lists#main'
   
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  after_update :update_done
  
  mount_uploader :image_url, DonepicUploader
  
  def completed?
    !completed_at.blank?
  end
  
  def update_done
    todo_list = self.todo_list
    todo_list.update(done: todo_list.todo_items.where(clear: true).count)
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, except: [:upload]
  before_action :set_todo_item, except: [:create, :upload]
  
  def create
    @todo_list.todo_items.create(todo_item_params)
    redirect_to :back
  end
    
  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo list item was deleted"
    else
      flash[:error] = "error"
    end
    redirect_to @todo_list
  end
  
  def complete
    #@todo_item = TodoItem.find(params[:id])
    #@todo_clear = TodoList.find(params[:id])
    #@todo_item.update(image_url: params[:pic])

    @todo_item.update_attribute(:completed_at, Time.now)  ##사진 저장 완료되면 할일 완료로 처리되는 부분
    #@todo_clear.current_user.done += 1                    ##할일 완료되면 todo_list.done(클리어 개수)이 1씩 증가
    flash[:notice]="donepic업로드완료"
    redirect_to @todo_list, notice: "Todo item completed"

  end
  
  def upload
    # uploader = DonepicUploader.new
    # uploader.store!(params[:pic])         
    # @todo_item.image_url = uploader.url
    todo_item = TodoItem.find(params[:id])
    todo_item.update(image_url: params[:pic])
    
    if todo_item.image_url.present?
      todo_item.update(completed_at: Time.now, clear: true)
      flash[:notice]="donepic업로드완료"
      redirect_to :back, notice: "Todo item completed"
	  else
      redirect_to :back
    end
  end
  

  private

  def set_todo_list
    @todo_list = current_user.todo_lists.find(params[:todo_list_id])
  end
  
  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
  
  def todo_item_params
    #params[:todo_item].permit(:item)
    params.require(:todo_item).permit(:item)
  end
  
  def set_time
    @date_time = Time.now
  end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_complete.html.erb
<% if todo_item.completed? %>


<% else %>
  <div class="complete">
    <span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>
    <form action="/todo_items/complete/<%= @todo_list.id %>" method ="post" enctype="multipart/form-data">
      <input type="file" name="pic" accept="/image/*">
      <input type="submit" value="완료">
    </form>
  </div>
<% end %>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
  <%= f.text_field :item, placeholder: "새 할일"  %>
  <%= f.submit '+' %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<!DOCTYPE html>
<html>
<head> 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
<script type="text/javascript">
  $( init );
  function init() {
    $('#item<%=todo_item.id%>').draggable();
  }
</script>

<style>
#makeMeDraggable { width: 300px; height: 300px; background: red; }
</style>

<script>
    $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
  
</script>
 
</head>

<body>
<div class="row clearfix">
  <% if todo_item.completed? %>
    <div class="card-panel hoverable" id="item<%=todo_item.id%>">
      <div class="todo_item">
        <p style="opacity:0.4;"><%= todo_item.item %></p>
          <!-- Modal Trigger -->
          <a class="waves-effect waves-light btn modal-trigger" href="#modal<%=todo_item.id%>">사진 보기</a>
          <!-- Modal Structure -->
          <div id="modal<%=todo_item.id%>" class="modal">
            <div class="modal-content">
              <h4>Modal Header</h4>
              <%= image_tag todo_item.image_url.thumb.url%>
            </div>
            <div class="modal-footer">
              <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>
          </div>
        
      </div>
      <div class="glyphicon glyphicon-search" aria-hidden="true">
        <%= link_to "삭제", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "are you sure?"} %>
      </div>
      
    </div>
    

    
  <% else %>
    <div class="todo_item">
      <div class="card-panel hoverable" id="item<%=todo_item.id%>">
      <p><%= todo_item.item %>
          <form action="/todo_items/upload/<%= todo_item.id %>" method ="post" enctype="multipart/form-data">
            <div class="file-field input-field">
              <div class="btn">
                <span>File</span>
                <input type="file"  name="pic" accept="/image/*">
                <input type="hidden" name="current_user">
                <input type="hidden" name="todo_list_id" value="<%= @todo_list.id %>">  <!--강제로 todo_list_id전송하고-->
                <input type="hidden" name="id" value="<%= todo_item.id %>">             <!--강제로 todo_item의 id 전송-->
                
              </div>
              <div class="file-path-wrapper">
                <input class="file-path validate" type="text" placeholder="사진을 첨부하세요">
              </div>
                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                  <i class="material-icons right">send</i>
                </button>
            </div>
          </form>
        
        <!--<form action="/todo_items/upload/<%= todo_item.id %>" method ="post" enctype="multipart/form-data">-->
        <!--  <input type="file" name="pic" accept="/image/*">-->
        <!--  <input type="hidden" name="current_user">-->
        <!--  <input type="hidden" name="todo_list_id" value="<%#= @todo_list.id %>">-->
        <!--  <input type="hidden" name="id" value="<%#= todo_item.id %>">-->
        <!--  <input type="submit" value="완료">-->
        <!--</form>-->
      </p>

  
    
    <div class="glyphicon glyphicon-trash" aria-hidden="true">
      <%= link_to "삭제", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "are you sure?"} %>
    </div>
   </div>
       </div>
    
  <% end %>
</div>



  

</body>
</html>

app/views/todo_items/_todo_item_end.html.erb
<% if todo_item.completed? %>
  <div class="todo_item">
    <p style="opacity:0.4;"><%= todo_item.item %></p>
  </div>
<% else %>
<!--활성화해줄 부분; 클릭이 가능해야함-->
  <div class="todo_item">
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item"><p><%= todo_item.item %></p></iframe>
  </div>
    
  </div>
  <!--선택된 할일들은 다음날 할일에 자동 추가-->
<% end %>