config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "callbacks", registrations: "users/registrations" }
  
  resources :todo_lists do
    resources :todo_items, :comments do
      member do
        patch :complete
      end
    end
  end
  
  root "todo_lists#index"
  post "todo_lists/comment" => "todo_lists#comment"
  #get "/todo_lists/:todo_list_id"
  get "/todo_items/complete"=>"todo_items#complete"
  #post "todo_items/complete" => "todo_items#complete"
  #post "" => "todo_items#complete"
  post "todo_items/upload/:id" => 'todo_items#upload', as: :todo_item_upload
  get '/mypage/home' => 'mypage#home'
  get 'mypage/check'
  get '/todo_lists/main' =>'todo_lists#main'
   
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
  has_many :comments
  belongs_to :user
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :main ,:edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  # 캘린더
  def index
    @todo_lists = current_user.todo_lists.all
    @meetings = Meeting.all
    @users = User.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  # 캘린더 클릭했을 때 할일판
  def show
    @todo_list = TodoList.find(params[:id])
    # @todo_friend = TodoList.last
    @comment = Comment.new
    @user = current_user 
    # @commentfind = Comment.find(params[:id])
    # @commentfind.user.nickname

  end

  def main
    @todo_list = current_user.todo_lists.last
  end
  
  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  # todo_list수정하는 거
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:date, :done)
    end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/todo_lists/_comment.html.erb
<%= form_for [@todo_list, @comment]  do |f| %>
  <div class="field">
    <%= f.text_field :content %>
    <%= f.submit '댓글달기' %>
  </div>
<% end %>

<!--염) 닉네임 만들려고 시도중. 호오이잉-->

<% @todo_list.comments.each do |c| %>
  <!--<%#= User.find(c.uid).nickname %>-->
  <%= @user.nickname %> | <%= c.content %> | <%= link_to '삭제', todo_list_comment_path(@todo_list, c), method: :delete %>
  <br>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<!DOCTYPE html>
<html>
<head>
  
</head>
<body>
<p id="notice"><%= notice %></p>

<h2>Listing Todo Lists</h2>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td><%= todo_list.date %></td>
        <td><%= todo_list.done %></td>
        <td><%= link_to 'Show', todo_list %></td>
        <!--<td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>-->
        <!--<td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

<%= month_calendar events: @meetings do |date, meetings| %>

  <%= date %>
  <% meetings.each do |meeting| %>
    <div>
      <%= meeting.name %>
    </div>
  <% end %>
<% end %>


<% @users.each do |user| %>
<p>닉네임: <%= user.nickname %></p>
<p>할일판: <a href="">할일판</a> </p>
<p>레벨: <></p>
<% end %>
</body>
</html>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<div class="row">
  <div class="col s4">
    <div class="container">
      <br><img src="/images/siba/level0.gif">
    </div>
  </div>
  
  <div class="col s4">
    <h4>
      <%= @todo_list.date.in_time_zone("Asia/Seoul").strftime("%m월 %d일") %>
      <strong>할일판</strong>
    </h4>
    <div style="box-sizing: border-box;">
      <!--Done: <%#= @todo_list.done %>-->
      <%= render @todo_list.todo_items %><br>
      <%= render "todo_items/form" %>
    </div>
  </div>
  
  <div class="col s4">
    <%= render "todo_lists/comment" %>
  </div>
</div>


<div class="container">
  <div class="field">
    <a href="/"><input type="submit" name="commit" value="뒤로 가기"></a>
  </div>  
</div>